name: "My Local Action"
description: "A simple local action to print a message"
inputs:
  message:
    description: "The message to print"
    required: true
    default: "Hello from my local action!"
runs:
  using: "node16"
  main: "index.js"
