name: AWS Secrets Manager Example

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  aws-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials 
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::585466297447:role/aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_bc53549516225ff5
          output-credentials: true
          
      - name: get caller identity 
        run: |
          aws sts get-caller-identity
