name: Demo Composite Action Workflow

on:
  # Manual trigger
  workflow_dispatch:

  push:
   branches:
    - gh-actions-training

jobs:
  demo-composite-action:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Use the composite action
      - name: Run Hello Composite Action
        uses: ./.github/actions/composite-action/action.yml
        with:
          my_name: "GitHub User"

      # Step 3: Use the composite action's output
      - name: Print Greeting Output
        run: echo "The composite action output was:" ${{ steps.greeting.outputs.greeting_message }}
