name: Demo Workflow

on: [workflow_dispatch]

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run a simple shell command
      - name: Say Hello
        run: echo "Hello from GitHub Actions on the ${{ github.ref_name }} branch!"

      # Step 3: Display GitHub context (optional for debugging/demo)
      - name: Print GitHub Context
        run: echo "Running on branch:" ${{ github.ref_name }}
