name: "Run Example Docker Action"

on:
  workflow_dispatch:
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p ~/.npm

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Run Docker Action
        uses: ./my-docker-action  # Path to the directory containing the action files
        with:
          example-input: "GitHub Actions"
