name: Docker Build and Push

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build JAR File
      - name: Build JAR File
        run: |
          cd app
          ./gradlew build

      # Step 2: Log in to GHCR
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push Docker image using docker/build-push-action
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: app/ # The directory containing your Dockerfile
          push: true # Push the built image to the registry
          tags: |
            ghcr.io/${{ github.actor }}/micronaut-app:latest
            ghcr.io/${{ github.actor }}/micronaut-app:${{ github.sha }}
