name: Docker Build and Push

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  
jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/my-app:latest -t ghcr.io/${{ github.actor }}/my-app:${{ github.sha::8 }} .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.actor }}/my-app:latest
          docker push ghcr.io/${{ github.actor }}/my-app:${{ github.sha::8 }}
