name: Use Environment Secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  use-environment-secret:
    runs-on: ubuntu-latest
    environment: development # Links this job to the "production" environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use the environment secret in a script
      - name: Access environment secret
        env:
          API_KEY: ${{ secrets.GH_ACTIONS_TRAINING_API_KEY }}
        run: |
          echo "Using the environment secret..."
          echo "The production API key is: $API_KEY"
