name: Local Action 

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-local-action:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies for the local action
      - name: Install dependencies for local action
        run: |
          cd ./.github/actions/my-local-action
          npm install

      # Step 3: Run the local action
      - name: Run My Local Action
        uses: ./.github/actions/my-local-action # Reference the local action         
