name: Node.js CI Logging

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create package.json
        run: |
          echo "::group::Creating package.json"
          echo '{
            "name": "github-actions-training",
            "version": "1.0.0",
            "scripts": {
              "test": "echo \"Running test...\"",
              "build": "echo \"Building project...\""
            }
          }' > package.json
          echo "::endgroup::"

      - name: Upload package.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-json
          path: package.json

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download package.json artifact
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Clean Install with npm ci
        run: npm ci

      - name: Run Build
        run: npm run build --if-present || echo "::warning::Build script not found."

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download package.json artifact
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: npm test || echo "::error::Tests failed. Check logs for details."
