name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Create package.json
      run: |
        echo '{
          "name": "github-actions-training",
          "version": "1.0.0",
          "scripts": {
            "test": "echo \"No test specified\" && exit 0",
            "build": "echo \"No build specified\" && exit 0"
          }
        }' > package.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
