name: Use Repository Secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  use-repository-secret:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use the repository secret in a script
      - name: Access repository secret
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          echo "Using the repository secret..."
          echo "The API key is: $API_KEY"
