name: Build and Save Artifacts

on:
  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Build the project
      run: go build -o myapp main.go

    - name: Package build artifacts
      run: |
        mkdir -p output
        echo "This is a build artifact!" > output/artifact.txt
        echo "Build complete!"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: output/
