name: Self-Hosted Runner Demo

on:
  # Trigger the workflow manually or on a push to the main branch
  workflow_dispatch:
  push:
    branches:
      - gh-actions-training

jobs:
  demo-job:
    name: Run on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display Runner Information
        run: echo "This job is running on a self-hosted runner!"
